    // --- MASTER EMOJI LIBRARY ---
    export const emojiMap = {
        
    // --- ACADEMIC SUBJECTS & LITERACY ---
    "alphabet": "🅰️",
    "calculate": "🧮",
    "experiment": "⚗️",
    "geography": "🌍",
    "history": "📜",
    "letter": "🅰️",
    "math": "➕",
    "reading": "📖",
    "science": "🧪",
    "spelling": "🔤",
    "word": "📝",
    "writing": "📝",

    // --- Fruits ---
    "apple": "🍎",
    "banana": "🍌",
    "blueberry": "🫐",
    "cherry": "🍒",
    "coconut": "🥥",
    "grape": "🍇",
    "green apple": "🍏",
    "kiwi": "🥝",
    "lemon": "🍋",
    "lime": "🍋‍🟩",
    "mango": "🥭",
    "melon": "🍈",
    "olive": "🫒",
    "orange": "🍊",
    "peach": "🍑",
    "pear": "🍐",
    "pineapple": "🍍",
    "strawberry": "🍓",
    "tomato": "🍅",
    "watermelon": "🍉",

    // --- Vegetables & Legumes ---
    "avocado": "🥑",
    "bean": "🫘",
    "bell pepper": "🫑",
    "broccoli": "🥦",
    "carrot": "🥕",
    "chestnut": "🌰",
    "corn": "🌽",
    "cucumber": "🥒",
    "eggplant": "🍆",
    "garlic": "🧄",
    "ginger": "🫚",
    "lettuce": "🥬",
    "mushroom": "🍄‍🟫",
    "onion": "🧅",
    "peanut": "🥜",
    "pepper": "🌶️",
    "potato": "🥔",
    "pea": "🫛",
    "root vegetable": "🫜",

    // --- ADJECTIVES & FEELINGS ---
    "angry": "😠",
    "bad": "❌",
    "big": "🐘",
    "cold": "❄️",
    "fast": "🐇",
    "good": "✅",
    "happy": "😊",
    "hot": "🔥",
    "sad": "😢",
    "slow": "🐢",
    "small": "🐜",
    "tired": "🥱",

    // --- ART & CREATIVITY ---
    "art": "🎨",
    "clay": "🏺",
    "color": "🌈",
    "draw": "🖍️",
    "glue": "🧴",
    "paint": "🖌️",
    "paper": "📄",

    // --- CLASSROOM ENVIRONMENT & FURNITURE ---
    "chair": "🪑",
    "clock": "⏰",
    "close": "🔒",
    "desk": "🪑",
    "door": "🚪",
    "enter": "🚶",
    "exit": "🚪",
    "hall": "🏢",
    "open": "🔓",
    "projector": "📽️",
    "shelf": "🗄️",
    "table": "🧱",
    "whiteboard": "⬜",

    // --- HEALTH, FOOD & PERSONAL CARE ---
    "apple": "🍎",
    "bathroom": "🚻",
    "cafeteria": "🍴",
    "drink": "🥤",
    "eat": "😋",
    "food": "🍎",
    "lunch": "🍱",
    "milk": "🥛",
    "nurse": "🏥",
    "tray": "🍱",
    "wash": "🧼",
    "water": "💧",

    // --- PEOPLE ---
    "adult": "🧑‍💼",
    "classmate": "🎒",
    "coach": "📣",
    "friend": "🤝",
    "kid": "🧒",
    "parent": "👪",
    "person": "👤",
    "principal": "👔",
    "staff": "🆔",
    "student": "🧑‍🎓",
    "teacher": "👩‍🏫",

    // --- SCHOOL SUPPLIES & MATERIALS ---
    "backpack": "🎒",
    "binder": "📁",
    "book": "📕",
    "computer": "💻",
    "eraser": "🧽",
    "folder": "📂",
    "homework": "🏠",
    "marker": "🖊️",
    "notebook": "📓",
    "pen": "🖋️",
    "pencil": "✏️",
    "phone": "📱",
    "ruler": "📏",
    "scissors": "✂️",
    "tablet": "📱",
    "test": "📑",

    // --- SENSES & COMMUNICATION ---
    "ear": "👂",
    "eye": "👁️",
    "find": "🔍",
    "hear": "👂",
    "listen": "👂",
    "look": "👀",
    "noise": "🔔",
    "quiet": "🤫",
    "see": "👁️",
    "sound": "🔊",
    "watch": "📺",

    // --- SEQUENCE & NUMBERS ---
    "after": "⏩",
    "before": "⏪",
    "count": "🔢",
    "end": "🏁",
    "first": "1️⃣",
    "five": "5️⃣",
    "four": "4️⃣",
    "lastly": "🔚",
    "next": "➡️",
    "one": "1️⃣",
    "order": "📋",
    "second": "2️⃣",
    "start": "🎬",
    "then": "🔜",
    "three": "3️⃣",
    "total": "📊",
    "two": "2️⃣",
    "zero": "0️⃣",

    // --- SPORTS, PE & RECESS ---
    "catch": "🤲",
    "climb": "🧗",
    "exercise": "🏋️",
    "game": "🎲",
    "gym": "🏀",
    "jump": "🦘",
    "play": "🛝",
    "run": "🏃",
    "sports": "⚽",
    "stretch": "🧘",
    "throw": "☄️",

    // --- TRANSPORTATION & PLACES ---
    "bus": "🚌",
    "coat": "🧥",
    "home": "🏠",
    "library": "📚",
    "line": "🚶‍♂️",
    "school": "🏫",
    "shoes": "👟",

    // --- VERBS & ACTIONS ---
    "clean": "🧹",
    "finish": "🏁",
    "give": "🎁",
    "go": "🟢",
    "help": "🤝",
    "like": "👍",
    "love": "❤️",
    "share": "🤲",
    "sing": "🎤",
    "sit": "🪑",
    "stand": "🧍",
    "stop": "🛑",
    "think": "🤔",
    "transition": "🔄",
    "wait": "⏳",
    "walk": "🚶",
    "work": "📁",
    "write": "✍️",

    // --- Phrasal Verbs & Multi-word Instructions ---
"take out": "📤",
"put away": "📥",
"hang up": "🧥",
"sit down": "🪑",
"stand up": "🧍",
"line up": "🚶‍♂️🚶‍♀️",
"pick up": "🧼",
"put down": "👇",
"clean up": "🧹",
"turn on": "💡",
"turn off": "🌑",
"look at": "👁️",
"listen to": "👂",
"throw away": "🗑️",

    // --- SWEETS & DESSERTS ---
    "birthday cake": "🎂",
    "candy": "🍬",
    "chocolate": "🍫",
    "cookie": "🍪",
    "cupcake": "🧁",
    "custard": "🍮",
    "donut": "🍩",
    "honey": "🍯",
    "ice cream": "🍦",
    "ice cream bowl": "🍨",
    "lollipop": "🍭",
    "pie": "🥧",
    "pudding": "🍮",
    "shaved ice": "🍧",
    "shortcake": "🍰",

    // --- DRINKS & DISHWARE ---
    "baby bottle": "🍼",
    "beer": "🍺",
    "beverage box": "🧃",
    "bubble tea": "🧋",
    "champagne": "🍾",
    "chopsticks": "🥢",
    "cocktail": "🍸",
    "coffee": "☕",
    "cup with straw": "🥤",
    "fork and knife": "🍴",
    "glass of wine": "🍷",
    "jar": "🫙",
    "juice": "🧃",
    "knife": "🔪",
    "mate": "🧉",
    "milk": "🥛",
    "plate": "🍽️",
    "pouring liquid": "🫗",
    "sake": "🍶",
    "soda": "🥤",
    "spoon": "🥄",
    "tea": "🍵",
    "teapot": "🫖",
    "tropical drink": "🍹",
    "whiskey": "🥃",

    // --- PREPARED FOODS ---
    "bacon": "🥓",
    "bagel": "🥯",
    "baguette": "🥖",
    "burrito": "🌯",
    "butter": "🧈",
    "cheese": "🧀",
    "cooking": "🍳",
    "croissant": "🥐",
    "egg": "🥚",
    "falafel": "🧆",
    "french fries": "🍟",
    "fried shrimp": "🍤",
    "hamburger": "🍔",
    "hot dog": "🌭",
    "meat on bone": "🍖",
    "pancakes": "🥞",
    "pasta": "🍝",
    "pizza": "🍕",
    "popcorn": "🍿",
    "poultry": "🍗",
    "pretzel": "🥨",
    "salad": "🥗",
    "salt": "🧂",
    "sandwich": "🥪",
    "soup": "🍲",
    "spaghetti": "🍝",
    "steak": "🥩",
    "taco": "🌮",
    "tamale": "🫔",
    "waffle": "🧇",

    // --- MAMMALS & MARSUPIALS ---
    "badger": "🦡",
    "bat": "🦇",
    "bear": "🐻",
    "beaver": "🦫",
    "bison": "🦬",
    "boar": "🐗",
    "camel": "🐪",
    "cat": "🐈",
    "cow": "🐄",
    "deer": "🦌",
    "dog": "🐕",
    "donkey": "🫏",
    "elephant": "🐘",
    "fox": "Fox",
    "giraffe": "🦒",
    "goat": "🐐",
    "gorilla": "🦍",
    "hamster": "🐹",
    "hedgehog": "🦔",
    "hippo": "🦛",
    "horse": "🐎",
    "kangaroo": "🦘",
    "koala": "🐨",
    "llama": "🦙",
    "lion": "🦁",
    "monkey": "🐒",
    "mouse": "🐭",
    "otter": "🦦",
    "ox": "🐂",
    "panda": "🐼",
    "pig": "🐷",
    "polar bear": "🐻‍❄️",
    "poodle": "🐩",
    "rabbit": "🐇",
    "raccoon": "🦝",
    "rat": "🐀",
    "rhino": "🦏",
    "sheep": "🐑",
    "skunk": "🦨",
    "sloth": "🦥",
    "squirrel": "🐿️",
    "tiger": "🐯",
    "unicorn": "🦄",
    "wolf": "🐺",
    "zebra": "🦓",

    // --- BIRDS ---
    "bird": "🐦",
    "chicken": "🐔",
    "duck": "🦆",
    "eagle": "🦅",
    "flamingo": "🦩",
    "goose": "🪿",
    "nest": "🪺",
    "owl": "🦉",
    "parrot": "🦜",
    "peacock": "🦚",
    "penguin": "🐧",
    "phoenix": "🐦‍🔥",
    "rooster": "🐓",
    "swan": "🦢",
    "turkey": " turkey",

    // --- MARINE & REPTILES ---
    "crocodile": "🐊",
    "dolphin": "🐬",
    "dragon": "🐉",
    "fish": "🐟",
    "frog": "🐸",
    "jellyfish": "🪼",
    "lobster": "🦞",
    "octopus": "🐙",
    "shark": "🦈",
    "shell": "🐚",
    "shrimp": "🦐",
    "snake": "🐍",
    "squid": "🦑",
    "turtle": "🐢",
    "whale": "🐳",

    // --- BUGS ---
    "ant": "🐜",
    "bee": "🐝",
    "beetle": "🪲",
    "butterfly": "🦋",
    "caterpillar": "🐛",
    "cricket": "🦗",
    "fly": "🪰",
    "ladybug": "🐞",
    "mosquito": "🦟",
    "scorpion": "🦂",
    "snail": "🐌",
    "spider": "🕷️",
    "worm": "🪱",

    // --- PLANTS & NATURE ---
    "cactus": "🌵",
    "deciduous tree": "🌳",
    "evergreen tree": "🌲",
    "flower": "🌸",
    "herb": "🌿",
    "leaf": "🍃",
    "mushroom": "🍄",
    "palm tree": "🌴",
    "potted plant": "🪴",
    "rock": "🪨",
    "rose": "🌹",
    "sunflower": "🌻",
    "tulip": "🌷",

    // --- SKY & WEATHER ---
    "cloud": "☁️",
    "comet": "☄️",
    "fire": "🔥",
    "lightning": "⚡",
    "moon": "🌙",
    "rainbow": "🌈",
    "rain": "🌧️",
    "snow": "❄️",
    "sun": "☀️",
    "tornado": "🌪️",
    "umbrella": "☂️",
    "wave": "🌊",
    "wind": "🌬️",

    // --- BUILDINGS & PLACES ---
    "bank": "🏦",
    "castle": "🏰",
    "church": "⛪",
    "factory": "🏭",
    "hospital": "🏥",
    "hotel": "🏨",
    "house": "🏠",
    "office": "🏢",
    "post office": "🏤",
    "school": "🏫",
    "stadium": "🏟️",
    "tent": "⛺",

    // --- LAND TRAVEL ---
    "ambulance": "🚑",
    "bicycle": "🚲",
    "bus": "🚌",
    "car": "🚗",
    "fire engine": "🚒",
    "motorcycle": "🏍️",
    "police car": "🚓",
    "skateboard": "🛹",
    "taxi": "🚕",
    "train": "🚂",
    "truck": "🚚",

    // --- AIR & SEA TRAVEL ---
    "airplane": "✈️",
    "anchor": "⚓",
    "boat": "⛵",
    "helicopter": "🚁",
    "rocket": "🚀",
    "ship": "🚢",

    // --- TOOLS & HOUSEHOLD ---
    "axe": "🪓",
    "broom": "🧹",
    "chair": "🪑",
    "flashlight": "🔦",
    "hammer": "🔨",
    "key": "🔑",
    "ladder": "🪜",
    "light bulb": "💡",
    "lock": "🔒",
    "mirror": "🪞",
    "soap": "🧼",
    "toilet": "🚽",
    "wrench": "🔧",

    // --- OFFICE & STATIONERY ---
    "calendar": "📅",
    "clipboard": "📋",
    "file folder": "📁",
    "notebook": "📓",
    "paperclip": "📎",
    "pencil": "✏️",
    "ruler": "📏",
    "scissors": "✂️",
    "trash can": "🗑️",

    // --- CLOTHING & APPEARANCE ---
    "backpack": "🎒",
    "coat": "🧥",
    "dress": "👗",
    "glasses": "👓",
    "hat": "👒",
    "jewelry": "💎",
    "shirt": "👕",
    "shoes": "👟",
    "tie": "👔",

    // --- MUSIC & SOUND ---
    "drum": "🥁",
    "guitar": "🎸",
    "headphones": "🎧",
    "microphone": "🎤",
    "piano": "🎹",
    "speaker": "🔊",
    "trumpet": "🎺",
    "violin": "🎻",

    // --- HANDS & BODY PARTS ---
    "arm": "💪",
    "brain": "🧠",
    "clap": "👏",
    "ear": "👂",
    "eye": "👁️",
    "foot": "👣",
    "hand": "✋",
    "heart": "🫀",
    "leg": "🦵",
    "nose": "👃",
    "smell": "👃",
    "smells": "👃",
    "point down": "👇",
    "point left": "👈",
    "point right": "👉",
    "point up": "👆",
    "pray": "🙏",
    "skeleton": "🦴",
    "thumbs down": "👎",
    "thumbs up": "👍",
    "tongue": "👅",
    "writing hand": "✍️"
    
    };
